modLoader = "javafml"
loaderVersion = "[0,)"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}, Kobalt, Were Fox, The Panda Oliver"
description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"